CREATE DATABASE Event_Management;
USE Event_Management;

CREATE TABLE Roles (
  RoleName VARCHAR(255) NOT NULL,
  Description VARCHAR(255),
  PRIMARY KEY (RoleName)
);

CREATE TABLE Users (
  UserID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Surname VARCHAR(50) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  BirthDate DATE NOT NULL,
  Role VARCHAR(255) NOT NULL DEFAULT "User",
  RegisterDate TIMESTAMP NOT NULL,
  EditDate TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (UserID),
  FOREIGN KEY (Role) REFERENCES Roles(RoleName) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Events (
  EventID INT NOT NULL AUTO_INCREMENT,
  Image VARCHAR(255) NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(255) NOT NULL,  
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  Seats INT NOT NULL,
  Place VARCHAR(255) NOT NULL,
  Price FLOAT NOT NULL,
  Organizer INT NOT NULL,
  Uploaded TIMESTAMP NOT NULL,
  PRIMARY KEY (EventID),
  FOREIGN KEY (Organizer) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Subscribers (
  SubscriberID INT NOT NULL AUTO_INCREMENT,
  Participant INT NOT NULL,
  Event INT NOT NULL,
  Date TIMESTAMP NOT NULL,
  PRIMARY KEY (SubscriberID),
  FOREIGN KEY (Participant) REFERENCES Users(UserID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (Event) REFERENCES Events(EventID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO Roles(RoleName, Description) VALUES ("User", "");
INSERT INTO Roles(RoleName, Description) VALUES ("Admin", "");
INSERT INTO Roles(RoleName, Description) VALUES ("Organizer", "");